# Generated by Django 4.2.7 on 2023-11-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_formdata_answer1_remove_formdata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='answer3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='answer4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='answer5',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
