# Generated by Django 4.2.7 on 2023-11-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formdata_selected_answer_alter_formdata_answer3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='selected_answer',
        ),
    ]
